// src/components/LightDarkSwitch.tsx
import { useEffect, useState } from "react";
import {
	MdOutlineBrightnessAuto,
	MdOutlineDarkMode,
	MdOutlineWbSunny,
} from "react-icons/md";
import { AUTO_MODE, DARK_MODE, LIGHT_MODE } from "@constants/constants.ts";
import I18nKey from "@i18n/i18nKey";
import { i18n } from "@i18n/translation";
import { applyStoredLanguage } from "@utils/lang-utils";
import {
	applyThemeToDocument,
	getStoredTheme,
	setTheme,
} from "@utils/setting-utils.ts";
import type { LIGHT_DARK_MODE } from "@/types/config.ts";

const seq: LIGHT_DARK_MODE[] = [LIGHT_MODE, DARK_MODE, AUTO_MODE];

export default function LightDarkSwitch() {
	const [mode, setMode] = useState<LIGHT_DARK_MODE>(AUTO_MODE);

	useEffect(() => {
		setMode(getStoredTheme());
		applyStoredLanguage();
	}, []);

	useEffect(() => {
		const darkModePreference = window.matchMedia("(prefers-color-scheme: dark)");
		const changeThemeWhenSchemeChanged = () => {
			applyThemeToDocument(mode);
		};
		darkModePreference.addEventListener("change", changeThemeWhenSchemeChanged);
		return () => {
			darkModePreference.removeEventListener(
				"change",
				changeThemeWhenSchemeChanged,
			);
		};
	}, [mode]);

	function switchScheme(newMode: LIGHT_DARK_MODE) {
		setMode(newMode);
		setTheme(newMode);
	}

	function toggleScheme() {
		const currentIndex = seq.findIndex((item) => item === mode);
		switchScheme(seq[(currentIndex + 1) % seq.length]);
	}

	return (
		<div
			className="relative z-50"
			role="menu"
			tabIndex={-1}
			onMouseLeave={() => {
				document
					.querySelector("#light-dark-panel")
					?.classList.add("float-panel-closed");
			}}
		>
			<button
				aria-label="Light/Dark Mode"
				role="menuitem"
				className="relative btn-plain scale-animation rounded-lg h-11 w-11 active:scale-90"
				id="scheme-switch"
				onClick={toggleScheme}
				onMouseEnter={() => {
					document
						.querySelector("#light-dark-panel")
						?.classList.remove("float-panel-closed");
				}}
			>
				<div className={`absolute ${mode !== LIGHT_MODE ? "opacity-0" : ""}`}>
					<MdOutlineWbSunny className="text-[1.25rem]" aria-hidden="true" />
				</div>
				<div className={`absolute ${mode !== DARK_MODE ? "opacity-0" : ""}`}>
					<MdOutlineDarkMode className="text-[1.25rem]" aria-hidden="true" />
				</div>
				<div className={`absolute ${mode !== AUTO_MODE ? "opacity-0" : ""}`}>
					<MdOutlineBrightnessAuto
						className="text-[1.25rem]"
						aria-hidden="true"
					/>
				</div>
			</button>

			<div
				id="light-dark-panel"
				className="hidden lg:block absolute transition float-panel-closed top-11 ltr:-right-2 rtl:-left-2 pt-5"
			>
				<div className="card-base float-panel p-2">
					<button
						className={`flex transition whitespace-nowrap items-center !justify-start w-full btn-plain scale-animation rounded-lg h-9 px-3 font-medium active:scale-95 mb-0.5 ${
							mode === LIGHT_MODE ? "current-theme-btn" : ""
						}`}
						onClick={() => switchScheme(LIGHT_MODE)}
					>
						<MdOutlineWbSunny
							className="text-[1.25rem] mr-3 rtl:mr-0 rtl:ml-3"
							aria-hidden="true"
						/>
						<span data-i18n="lightMode">{i18n(I18nKey.lightMode)}</span>
					</button>
					<button
						className={`flex transition whitespace-nowrap items-center !justify-start w-full btn-plain scale-animation rounded-lg h-9 px-3 font-medium active:scale-95 mb-0.5 ${
							mode === DARK_MODE ? "current-theme-btn" : ""
						}`}
						onClick={() => switchScheme(DARK_MODE)}
					>
						<MdOutlineDarkMode
							className="text-[1.25rem] mr-3 rtl:mr-0 rtl:ml-3"
							aria-hidden="true"
						/>
						<span data-i18n="darkMode">{i18n(I18nKey.darkMode)}</span>
					</button>
					<button
						className={`flex transition whitespace-nowrap items-center !justify-start w-full btn-plain scale-animation rounded-lg h-9 px-3 font-medium active:scale-95 ${
							mode === AUTO_MODE ? "current-theme-btn" : ""
						}`}
						onClick={() => switchScheme(AUTO_MODE)}
					>
						<MdOutlineBrightnessAuto
							className="text-[1.25rem] mr-3 rtl:mr-0 rtl:ml-3"
							aria-hidden="true"
						/>
						<span data-i18n="systemMode">{i18n(I18nKey.systemMode)}</span>
					</button>
				</div>
			</div>
		</div>
	);
}

// src/components/LightDarkSwitch.svelte
<script lang="ts">
import { AUTO_MODE, DARK_MODE, LIGHT_MODE } from "@constants/constants.ts";
import I18nKey from "@i18n/i18nKey";
import { i18n } from "@i18n/translation";
import Icon from "@iconify/svelte";
import { applyStoredLanguage } from "@utils/lang-utils";
import {
	applyThemeToDocument,
	getStoredTheme,
	setTheme,
} from "@utils/setting-utils.ts";
import { onMount } from "svelte";
import type { LIGHT_DARK_MODE } from "@/types/config.ts";

interface Props {}

let {}: Props = $props();

const seq: LIGHT_DARK_MODE[] = [LIGHT_MODE, DARK_MODE, AUTO_MODE];
let mode: LIGHT_DARK_MODE = $state(AUTO_MODE);

onMount(() => {
	mode = getStoredTheme();
    applyStoredLanguage();
	const darkModePreference = window.matchMedia("(prefers-color-scheme: dark)");
	const changeThemeWhenSchemeChanged: Parameters<
		typeof darkModePreference.addEventListener<"change">
	>[1] = (_e) => {
		applyThemeToDocument(mode);
	};
	darkModePreference.addEventListener("change", changeThemeWhenSchemeChanged);
	return () => {
		darkModePreference.removeEventListener(
			"change",
			changeThemeWhenSchemeChanged,
		);
	};
});

function switchScheme(newMode: LIGHT_DARK_MODE) {
	mode = newMode;
	setTheme(newMode);
}

function toggleScheme() {
	let i = 0;
	for (; i < seq.length; i++) {
		if (seq[i] === mode) {
			break;
		}
	}
	switchScheme(seq[(i + 1) % seq.length]);
}

function showPanel() {
	const panel = document.querySelector("#light-dark-panel");
    panel?.classList.remove("float-panel-closed");
}

function hidePanel() {
	const panel = document.querySelector("#light-dark-panel");
    panel?.classList.add("float-panel-closed");
}
</script>

<!-- z-50 make the panel higher than other float panels -->
<div class="relative z-50" role="menu" tabindex="-1" onmouseleave={hidePanel}>
    <button aria-label="Light/Dark Mode" role="menuitem" class="relative btn-plain scale-animation rounded-lg h-11 w-11 active:scale-90" id="scheme-switch" onclick={toggleScheme} onmouseenter={showPanel}>
        <div class="absolute" class:opacity-0={mode !== LIGHT_MODE}>
            <Icon icon="material-symbols:wb-sunny-outline-rounded" class="text-[1.25rem]"></Icon>
        </div>
        <div class="absolute" class:opacity-0={mode !== DARK_MODE}>
            <Icon icon="material-symbols:dark-mode-outline-rounded" class="text-[1.25rem]"></Icon>
        </div>
        <div class="absolute" class:opacity-0={mode !== AUTO_MODE}>
            <Icon icon="material-symbols:radio-button-partial-outline" class="text-[1.25rem]"></Icon>
        </div>
    </button>

    <div id="light-dark-panel" class="hidden lg:block absolute transition float-panel-closed top-11 ltr:-right-2 rtl:-left-2 pt-5" >
        <div class="card-base float-panel p-2">
            <button class="flex transition whitespace-nowrap items-center !justify-start w-full btn-plain scale-animation rounded-lg h-9 px-3 font-medium active:scale-95 mb-0.5"
                    class:current-theme-btn={mode === LIGHT_MODE}
                    onclick={() => switchScheme(LIGHT_MODE)}
            >
                <Icon icon="material-symbols:wb-sunny-outline-rounded" class="text-[1.25rem] mr-3 rtl:mr-0 rtl:ml-3"></Icon>
                <span data-i18n="lightMode">{i18n(I18nKey.lightMode)}</span>
            </button>
            <button class="flex transition whitespace-nowrap items-center !justify-start w-full btn-plain scale-animation rounded-lg h-9 px-3 font-medium active:scale-95 mb-0.5"
                    class:current-theme-btn={mode === DARK_MODE}
                    onclick={() => switchScheme(DARK_MODE)}
            >
                <Icon icon="material-symbols:dark-mode-outline-rounded" class="text-[1.25rem] mr-3 rtl:mr-0 rtl:ml-3"></Icon>
                <span data-i18n="darkMode">{i18n(I18nKey.darkMode)}</span>
            </button>
            <button class="flex transition whitespace-nowrap items-center !justify-start w-full btn-plain scale-animation rounded-lg h-9 px-3 font-medium active:scale-95"
                    class:current-theme-btn={mode === AUTO_MODE}
                    onclick={() => switchScheme(AUTO_MODE)}
            >
                <Icon icon="material-symbols:radio-button-partial-outline" class="text-[1.25rem] mr-3 rtl:mr-0 rtl:ml-3"></Icon>
                <span data-i18n="systemMode">{i18n(I18nKey.systemMode)}</span>
            </button>
        </div>
    </div>
</div>
